services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PostgreUser}
      POSTGRES_PASSWORD: ${PostgrePassword}
      POSTGRES_DB: ${PostgreDB}
    ports:
    - ${PostgrePort}:5432
    volumes:
    - db:/var/lib/postgresql/data
    networks:
      - cloudvault_network
  
  backend: 
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: vault_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - PostgreUser=${PostgreUser}
      - PostgrePassword=${PostgrePassword}
      - PostgreDB=${PostgreDB}
      - PostgrePort=5432
      - PostgreHost=${PostgreHost}
    depends_on:
      - postgres
    networks:
      - cloudvault_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: vault_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5030"
    volumes:
      - ./frontend:/app:rw
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - cloudvault_network

volumes:
  db:

networks: 
  cloudvault_network: